import type {
  AppPreferences,
  CurriculumResponse,
  EnergyFacet,
  GameState,
  LessonSummary,
  ServiceStatus,
} from './types'

export const DEFAULT_PREFERENCES: AppPreferences = {
  board_size: 9,
  mode: 'human_companion',
  black_agent: { persona: 'Mountain', doctrine: 'territory' },
  white_agent: { persona: 'River', doctrine: 'balanced' },
  companion: { persona: 'Lantern', style: 'socratic' },
  reduced_motion: false,
  coordinates: true,
}

export const FALLBACK_STATUS: ServiceStatus = {
  status: 'degraded',
  engine: {
    status: 'fallback',
    provider: 'KataGo',
    detail: 'Analysis is not connected. Exact board teaching remains available.',
  },
  coach: {
    status: 'fallback',
    provider: 'Local companion',
    detail: 'Using authored lesson guidance.',
  },
  supported_board_sizes: [5, 7, 9],
}

const lessons: LessonSummary[] = [
  {
    id: 'first-breath',
    order: 1,
    title: 'First Breath',
    subtitle: 'See how a stone stays alive',
    story: 'A lone scout enters the small valley. Find every road that keeps it breathing.',
    board_size: 5,
    duration_minutes: 6,
    concepts: ['Liberties', 'Atari', 'Capture'],
    difficulty: 'first_steps',
    status: 'complete',
    training_variant: 'first_capture',
    memory_line: 'Count the whole string’s distinct liberties.',
  },
  {
    id: 'bridge-builders',
    order: 2,
    title: 'Bridge Builders',
    subtitle: 'Connect before the road closes',
    story: 'Two allies can see each other across the river, but White may reach the bridge first.',
    board_size: 7,
    duration_minutes: 8,
    concepts: ['Connection', 'Cutting', 'Shape'],
    difficulty: 'first_steps',
    status: 'current',
    memory_line: 'Connected stones share their breath.',
  },
  {
    id: 'opening-compass',
    order: 3,
    title: 'Opening Compass',
    subtitle: 'Choose a promise on the real board',
    story: 'The nine-line valley opens. Choose ground, reach, or balance—then explain your promise.',
    board_size: 9,
    duration_minutes: 12,
    concepts: ['Opening', 'Intent', 'Influence'],
    difficulty: 'beginner',
    status: 'available',
    memory_line: 'A first move is a promise, not territory yet.',
  },
  {
    id: 'two-lanterns',
    order: 4,
    title: 'Two Lanterns',
    subtitle: 'Build a shelter that cannot be darkened',
    story: 'One long chamber is fragile. Raise a pillar and keep two lights alive.',
    board_size: 7,
    duration_minutes: 10,
    concepts: ['Eyes', 'Life & death', 'Vital point'],
    difficulty: 'beginner',
    status: 'available',
    memory_line: 'Two independent eyes live.',
  },
  {
    id: 'mist-and-ground',
    order: 5,
    title: 'Mist and Ground',
    subtitle: 'Feel influence without calling it territory',
    story: 'Some land is settled. Some is only a possibility. Learn to tell stone from mist.',
    board_size: 9,
    duration_minutes: 14,
    concepts: ['Influence', 'Territory', 'Sente'],
    difficulty: 'growing',
    status: 'available',
    memory_line: 'Influence is potential, not points in the bank.',
  },
  {
    id: 'hunt-run-settle',
    order: 6,
    title: 'Hunt, Run, Settle',
    subtitle: 'Attack without needing to kill',
    story: 'The chase begins. Decide whether to advance, dodge, flee, or build shelter.',
    board_size: 9,
    duration_minutes: 16,
    concepts: ['Attack', 'Escape', 'Sacrifice'],
    difficulty: 'growing',
    status: 'available',
    memory_line: 'Attack to gain; killing is only one possible gain.',
  },
]

export const FALLBACK_CURRICULUM: CurriculumResponse = {
  version: 'authored-fallback-v1',
  title: 'Path of Influence',
  lessons,
}

export const DEMO_FACETS: EnergyFacet[] = [
  {
    id: 'breath',
    label: 'Breath',
    canonical_term: 'Liberties',
    value: '3 open roads',
    change: '+2',
    evidence: 'exact',
    explanation: 'The selected string would have three distinct liberties.',
  },
  {
    id: 'bonds',
    label: 'Bonds',
    canonical_term: 'Connection',
    value: 'One string',
    evidence: 'exact',
    explanation: 'The move joins adjacent stones into one connected string.',
  },
  {
    id: 'reach',
    label: 'Reach',
    canonical_term: 'Influence',
    value: 'Toward the center',
    evidence: 'engine',
    explanation: 'A bounded engine estimate suggests pressure toward the open center.',
  },
  {
    id: 'beat',
    label: 'Turn',
    canonical_term: 'Side to move',
    value: 'Black to move',
    evidence: 'exact',
    explanation: 'The side to move is exact; a reply is forcing only when ignoring it has a concrete cost.',
  },
]

export const DEMO_GAME: GameState = {
  id: 'local-preview',
  title: 'Opening Compass',
  mode: 'human_companion',
  board_size: 9,
  phase: 'playing',
  move_count: 0,
  updated_at: new Date(0).toISOString(),
  lesson_id: 'opening-compass',
  lesson_title: 'Opening Compass',
  concepts: ['Intent', 'Connection', 'Influence'],
  revision: 1,
  to_play: 'black',
  rules: {
    name: 'Chinese area rules',
    scoring: 'chinese_area',
    ko_rule: 'positional_superko',
    komi: 7.5,
  },
  stones: [
    { x: 2, y: 6, color: 'black' },
    { x: 6, y: 2, color: 'white' },
    { x: 3, y: 5, color: 'black' },
    { x: 5, y: 3, color: 'white' },
    { x: 2, y: 5, color: 'black' },
    { x: 6, y: 3, color: 'white' },
    { x: 3, y: 6, color: 'black' },
    { x: 5, y: 2, color: 'white' },
  ],
  moves: [],
  actors: [
    { id: 'human', name: 'You', role: 'human', color: 'black' },
    {
      id: 'sparring-agent',
      name: 'River',
      role: 'player_agent',
      color: 'white',
      doctrine: 'balanced',
    },
    {
      id: 'companion',
      name: 'Lantern',
      role: 'companion_agent',
      aligned_with: 'black',
      personality: 'Socratic and warm',
    },
  ],
  objective: 'Choose a move with a clear intention, then name what it changes.',
  act: 'Contact · Two groups are taking shape',
  area_snapshot: {
    status: 'mechanical_all_stones_alive',
    black_stones: 4,
    black_enclosed_empty: 0,
    black_total: 4,
    white_stones: 4,
    white_enclosed_empty: 0,
    komi: 7.5,
    white_total: 11.5,
    neutral_points: 73,
    adjudicated: false,
  },
  coach_history_next_cursor: null,
  coach_messages: [
    {
      id: 'welcome',
      speaker: 'Lantern',
      role: 'companion',
      text: 'Your lower group has room to breathe. Before moving, ask whether you want ground, connection, or reach.',
      prompt: 'Which promise should your next stone make?',
    },
  ],
  analysis: {
    status: 'fallback',
    engine: 'Authored setup; no live position analysis',
    facets: [],
    candidates: [],
  },
}
