from __future__ import annotations

from copy import deepcopy
from typing import Any

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "id": "breath-5",
        "order": 0,
        "board_size": 5,
        "title": "The Last Breath",
        "subtitle": "See liberties before you see battles",
        "estimated_minutes": 4,
        "variant": "first_capture",
        "training_rule": (
            "This guided scene focuses on the first capture and escape decision; "
            "the live game still ends only under the declared Go rules."
        ),
        "concepts": ["liberties", "atari", "escape"],
        "story_hook": "A lone scout has one road left. Find the road before the ring closes.",
        "objective": "Give the black stone at C3 more than one liberty.",
        "memory": "When a string is in atari, ask: extend, connect, capture, or sacrifice deliberately.",
        "setup": {"black": ["C3"], "white": ["B3", "C2", "D3"], "to_play": "B"},
        "featured_moves": ["C4"],
        "available": True,
    },
    {
        "id": "bridge-5",
        "order": 1,
        "board_size": 5,
        "title": "The Bridge",
        "subtitle": "Connection shares breath",
        "estimated_minutes": 5,
        "variant": "guided_position",
        "training_rule": None,
        "concepts": ["connection", "cutting_point", "shape"],
        "story_hook": "Two allies can see one another, but an open crossing lies between them.",
        "objective": "Connect the black stones at B3 and D3.",
        "memory": "Connected means directly adjacent along a line, not merely nearby.",
        "setup": {"black": ["B3", "D3"], "white": [], "to_play": "B"},
        "featured_moves": ["C3"],
        "available": True,
    },
    {
        "id": "roads-7",
        "order": 2,
        "board_size": 7,
        "title": "Roads Through the Mist",
        "subtitle": "Run, settle, or turn and fight",
        "estimated_minutes": 8,
        "variant": "guided_position",
        "training_rule": None,
        "concepts": ["weak_groups", "escape", "base"],
        "story_hook": "Your small group is pressed against the eastern ridge. Choose what survival means.",
        "objective": "Create room for the marked black group without making a second weak group.",
        "memory": "A running group needs open roads; a settled group needs shelter.",
        "setup": {
            "black": ["E3", "E4"],
            "white": ["D3", "D4", "F2"],
            "to_play": "B",
        },
        "featured_moves": ["F4", "E5", "G3"],
        "available": True,
    },
    {
        "id": "opening-compass",
        "order": 3,
        "board_size": 9,
        "title": "Choose a Promise",
        "subtitle": "Your first real 9×9 opening",
        "estimated_minutes": 10,
        "variant": "go",
        "training_rule": None,
        "concepts": ["opening", "influence", "territory", "intention"],
        "story_hook": "The valley is empty. Your first stone does not own it—it makes a promise.",
        "objective": "Choose any legal opening and name the intention behind it.",
        "memory": "A first move is a promise, not territory already owned.",
        "setup": {"black": [], "white": [], "to_play": "B"},
        "featured_moves": ["E5", "C3", "E3"],
        "available": True,
    },
    {
        "id": "first-expedition",
        "order": 4,
        "board_size": 9,
        "title": "First Expedition",
        "subtitle": "Finish a complete game with a quiet companion",
        "estimated_minutes": 18,
        "variant": "go",
        "training_rule": None,
        "concepts": ["full_game", "pass", "chinese_area_scoring"],
        "story_hook": "This time the road will not end at one capture. Carry the position to its true ending.",
        "objective": (
            "Play until both sides pass, inspect the mechanical area snapshot, "
            "and identify unsettled groups before calling a final score."
        ),
        "memory": "Two passes end play; settle dead stones before declaring the final margin.",
        "setup": {"black": [], "white": [], "to_play": "B"},
        "featured_moves": ["C3", "G7", "E5"],
        "available": True,
    },
    {
        "id": "shape-of-power",
        "order": 5,
        "board_size": 9,
        "title": "The Shape of Power",
        "subtitle": "Influence is potential, not points in the bank",
        "estimated_minutes": 16,
        "variant": "go",
        "training_rule": None,
        "concepts": ["thickness", "influence", "territory", "direction"],
        "story_hook": "One side has walls; the other has ground. Neither form of power is complete alone.",
        "objective": "Use a strong outside position without overclaiming uncertain ground.",
        "memory": "Thickness is useful when it faces something worth influencing.",
        "setup": {"black": [], "white": [], "to_play": "B"},
        "featured_moves": ["E5", "C4", "G6"],
        "available": True,
    },
    {
        "id": "river-chronicle",
        "order": 6,
        "board_size": 9,
        "title": "River Chronicle",
        "subtitle": "A complete narrated capstone",
        "estimated_minutes": 24,
        "variant": "go",
        "training_rule": None,
        "concepts": ["complete_game", "review", "reflection"],
        "story_hook": "Play the game, then retell its promise, crisis, settlement, and last light.",
        "objective": "Complete and review a 9×9 game without requiring the engine's best move.",
        "memory": "The strongest review finds one reusable principle, not a list of punishments.",
        "setup": {"black": [], "white": [], "to_play": "B"},
        "featured_moves": ["C3", "E5", "G3"],
        "available": True,
    },
    {
        "id": "wide-river-13",
        "order": 7,
        "board_size": 13,
        "title": "The Wider River",
        "subtitle": "A later bridge toward the full board",
        "estimated_minutes": 35,
        "variant": "go",
        "training_rule": None,
        "concepts": ["whole_board", "direction", "tenuki"],
        "story_hook": "More space means more choices—and more permission to leave a local fight.",
        "objective": "Bridge lesson reserved for later progression.",
        "memory": "A bigger board rewards direction before detail.",
        "setup": {"black": [], "white": [], "to_play": "B"},
        "featured_moves": [],
        "available": False,
    },
    {
        "id": "full-landscape-19",
        "order": 8,
        "board_size": 19,
        "title": "The Full Landscape",
        "subtitle": "Optional long-board study",
        "estimated_minutes": 60,
        "variant": "go",
        "training_rule": None,
        "concepts": ["whole_board", "opening", "large_scale_strategy"],
        "story_hook": "The full landscape waits until the smaller valleys feel readable.",
        "objective": "Optional advanced journey; never the beginner default.",
        "memory": "Board size changes scale, not the meaning of liberties and connection.",
        "setup": {"black": [], "white": [], "to_play": "B"},
        "featured_moves": [],
        "available": False,
    },
)


def list_lessons() -> list[dict[str, Any]]:
    return deepcopy(list(LESSONS))


def get_lesson(lesson_id: str) -> dict[str, Any] | None:
    for lesson in LESSONS:
        if lesson["id"] == lesson_id:
            return deepcopy(lesson)
    return None
